spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/RescueMeDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: "rescueme.care@gmail.com"
    password: "ya29.a0AeXRPp5wx3gsB_JY8AgLDY37fB4DAto4cxs_w0aNtrE1iPYPilBU_TJAcqZx7TTsD0ckAcnRPzi3oIihe2rVN2-mgCZHk9ei89ZOwznQy2uy0yWuT2JsEy0Oz6NG_fRVtXpL5lDNi6BM_Y0qQ3CU-f1bFfu4XbJIR4ArcW_CaCgYKAdUSARMSFQHGX2Mi8BqTzHV-4hB9_qs2u2BmkQ0175"
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
        smtp.auth.mechanisms: XOAUTH2

jwt:
  secret: mySuperSecretKey12345678901234567890


cors:
  allowedOrigins: "http://localhost:5173"
  allowedMethods: "*"
  allowedHeaders: "*"


