spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "rescueme.care@gmail.com"
    password: "ya29.a0AeXRPp5wx3gsB_JY8AgLDY37fB4DAto4cxs_w0aNtrE1iPYPilBU_TJAcqZx7TTsD0ckAcnRPzi3oIihe2rVN2-mgCZHk9ei89ZOwznQy2uy0yWuT2JsEy0Oz6NG_fRVtXpL5lDNi6BM_Y0qQ3CU-f1bFfu4XbJIR4ArcW_CaCgYKAdUSARMSFQHGX2Mi8BqTzHV-4hB9_qs2u2BmkQ0175"
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
        smtp.auth.mechanisms: XOAUTH2

jwt:
  secret: mySuperSecretKey1234567890123456789012345679

stripe:
  api:
    key: sk_test_51PMAPoFShGT4VhrkFhZZDAo75tfPaW0fFoFv84ZCDcmwPomPWOjRnguiXZPhS7yRprH2qa88ykzKv5UDiTldiawQ00WHLXbyU1
    publishable: pk_test_51PMAPoFShGT4VhrkhvsCFVXqOxPUBOOgsR3Lmh6ye38uiCYwpgvfBUeFqrADQ9xhnXlUEe41xRsi8WMh918AB1A500FvDbAA4d
  webhook:
    secret: whsec_d5846ac1207998671a57121d6f99bafbac6e6c13ea6c1a11198ad2883a77a60b


cors:
  allowedOrigins: "http://localhost:5173"
  allowedMethods: "*"
  allowedHeaders: "*"


